# Generated by Django 4.0.4 on 2022-06-10 06:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=12)),
                ('left', models.IntegerField(default=0)),
                ('top', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='KeywordLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_keyword', models.UUIDField()),
                ('from_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='note.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='note.note'),
        ),
    ]
