# Generated by Django 2.0.1 on 2022-05-28 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', models.TextField()),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
