# Generated by Django 4.0.4 on 2022-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
