# Generated by Django 4.0.4 on 2022-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
