# Generated by Django 4.0.4 on 2022-06-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordlink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
