# Generated by Django 4.0.4 on 2022-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_keyword_left_alter_keyword_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='link_to',
            field=models.ManyToManyField(to='document.keyword'),
        ),
    ]
