# Generated by Django 4.0.4 on 2022-05-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20220528_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
