# Generated by Django 4.0.4 on 2022-05-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
